spring:
  kafka:
    # Адрес для подключения к Kafka
    bootstrap-servers: ${KAFKA_HOST}:${KAFKA_PORT}, ${KAFKA_2_HOST}:${KAFKA_2_PORT}
    consumer:
      group-id: 1
    template:
      topic-name: newTopic
