server:
  port: 8081
spring:
  kafka:
    # Адрес для подключения к Kafka
    bootstrap-servers: localhost:19092, localhost:19093
    consumer:
      group-id: 1
    template:
      topic-name: newTopic
