spring:
  kafka:
    # Адрес для подключения к Kafka
    bootstrap-servers: ${KAFKA_HOST}:${KAFKA_PORT}, ${KAFKA_2_HOST}:${KAFKA_2_PORT}
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
    topic: newTopic
